### ISSUE TITLE
Auto Obstacles 

### ISSUE THREAD

**Issue by Spiderpig02** [Spiderpig02/GalacticPathFinder#18]
As a user, I want the possibility of clicking a button and generating some obstacles on the map, so that I don't have to create obstacles manually by placing them on the map. 

**Acceptance Criteria:**
- [x] Generate obstacles automatically based on the map's size
- [x] Generate the obstacles automatically using Perlin Noise

**Comment by SverreNystad** [comment]
Have been thinking of the same thing. This would be a very nice feature for the user. Should It be random patterns on the map? And or should there be presets?
