### ISSUE TITLE
Maze generation

### ISSUE THREAD

**Issue by SverreNystad** [Spiderpig02/GalacticPathFinder#24]
It would be very cool to make to be able to create a maze for the pathfinding algorithms to escape out of

**Comment by Jitanshu-commits** [comment]
I could help you depending on what you need.

**Comment by SverreNystad** [comment]
Greetings @Jitanshu-commits. Nice to see that you have taken an interest in the project. We are currently trying to create the frontend part and deployment of the project today.

**Comment by Jitanshu-commits** [comment]
can you give me a link to the exact code repository that I need to make changes in the pull requests?
