### ISSUE TITLE
Make "About-us" page / cedits page 

### ISSUE THREAD

**Issue by Jensern1** [Spiderpig02/GalacticPathFinder#66]

**Comment by SverreNystad** [comment]
![image](https://github.com/user-attachments/assets/c02f5ce3-37c1-49dc-bbd4-a6c268a2a214)

**Comment by SverreNystad** [comment]
![image](https://github.com/user-attachments/assets/c4110429-8fa7-46da-84c1-61923b9593ae)
I added a button to come their

**Comment by SverreNystad** [comment]
@Jensern1 @Spiderpig02 could you go over the text and make the changes you require before closing the issue?

**Comment by SverreNystad** [comment]
As this is in prod i mark it as finished
